import { get, request } from "../core/request"

import { FoiaRequestStatus } from "../daos/copa-cases-dao"
import { getSessionToken } from "../aws-facades/sts-facade"
import got from "got"

export interface CommFile {
    id: number
    ffile: string
    datetime: string
    title: string
    source: string
    description: string
    access: string
    doc_id: string
    pages: number
}

export interface RequestComm {
    foia: number
    from_user: number
    to_user: number
    subject: string
    datetime: string
    response: boolean
    autogenerated: boolean
    thanks: boolean
    full_html: boolean
    communication: string
    status: string
    likely_foia: any
    files: CommFile[]
    delivered: string
}

export interface FoiaRequest {
    id: string
    title: string
    slug: string
    status: string
    embargo: boolean
    permanent_embargo: boolean
    user: number
    username: string
    agency: number
    datetime_submitted: string
    date_due: string
    days_until_due: any
    date_followup: any
    datetime_done: string
    date_embargo: any
    tracking_id: string
    price: string
    disable_autofollowups: boolean
    tags: string[]
    communications: RequestComm[]
}

export interface GetFoiaRequestProps {
    id: string
}

export const getFoiaRequest = async ({ id }: GetFoiaRequestProps): Promise<FoiaRequest | undefined> => {
    try {
        const res = await got.get(`https://muckrock.com/api_v1/foia/${id}`, {
            responseType: "json"
        })
        return res.body as FoiaRequest
    } catch (err) {
        if (err.message != "Response code 404 (Not Found)") {
            throw err
        }
    }
    return undefined
}
