import got from "got"

export interface CommFile {
    id: number
    ffile: string
    datetime: string
    title: string
    source: string
    description: string
    access: string
    doc_id: string
    pages: number
}

export interface RequestComm {
    foia: number
    from_user: number
    to_user: number
    subject: string
    datetime: string
    response: boolean
    autogenerated: boolean
    thanks: boolean
    full_html: boolean
    communication: string
    status: string
    likely_foia: number
    files: CommFile[]
    delivered: string
}

export interface FoiaRequest {
    id: string
    title: string
    slug: string
    status: string
    embargo: boolean
    permanent_embargo: boolean
    user: number
    username: string
    agency: number
    datetime_submitted: string
    date_due: string
    days_until_due: number
    date_followup: string
    datetime_done: string
    date_embargo: string
    tracking_id: string
    price: string
    disable_autofollowups: boolean
    tags: string[]
    communications: RequestComm[]
}

export interface GetFoiaRequestProps {
    id: string
}

export const getFoiaRequest = async ({ id }: GetFoiaRequestProps): Promise<FoiaRequest | undefined> => {
    try {
        const res = await got.get(`https://muckrock.com/api_v1/foia/${id}`, {
            responseType: "json"
        })
        return res.body as FoiaRequest
    } catch (err) {
        if (err.message != "Response code 404 (Not Found)") {
            throw err
        }
    }
    return undefined
}

export interface CreateFoiaRequestProps {
    apiToken: string
    title: string
    agency: string
    documentRequest: string
}

export const createFoiaRequest = async ({
    apiToken,
    title,
    agency,
    documentRequest
}: CreateFoiaRequestProps): Promise<unknown> => {
    try {
        const res = await got.post(`https://muckrock.com/api_v1/foia`, {
            headers: { Authorization: `Token ${apiToken}`, "content-type": "application/json" },
            body: JSON.stringify({ title, agency, document_request: documentRequest }),
            responseType: "json"
        })
        return res.body
    } catch (err) {
        if (err.message != "Response code 404 (Not Found)") {
            throw err
        }
    }
    return undefined
}
